module.exports = {
  people: getPeople()
};

function getPeople() {
  return [
    { id: 1, firstName: 'John', lastName: 'Smith', age: 25, location: 'Florida' ,
      experience:[{Title:'Director, Software Engineering',
        companyInfo:'ACME Systems, Concord, MA',
        description:'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque eu tempor sapien, id mattis nulla. Suspendisse nec lectus eros. Aenean convallis eros nec'},
        {Title:'Software Developer',companyInfo:'Universe Exports, Billerica, MA',description:'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque eu tempor sapien, id mattis nulla. Suspendisse nec'},
        {Title:'Software Specialist',companyInfo:'Universe Exports, Billerica, MA',description:'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque eu tempor sapien, id mattis nulla. Suspendisse nec.'}],
        education:[{school:'Rocheseter Institute,', degree:'Bachelor of Engineer, New Haven, CT'},{school: 'Albertus Magnus Tech', degree:'Engineering Degree, New Haven, CT' }]},
    { id: 2, firstName: 'Ward', lastName: 'Bell', age: 31, location: 'California',
      experience:[{Title:'Director, Software Engineering',
        companyInfo:'ACME Systems, Concord, MA',
        description:'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque eu tempor sapien, id mattis nulla. Suspendisse nec lectus eros. Aenean convallis eros nec'},
        {Title:'Software Developer',companyInfo:'Universe Exports, Billerica, MA',description:'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque eu tempor sapien, id mattis nulla. Suspendisse nec'},
        {Title:'Software Specialist',companyInfo:'Universe Exports, Billerica, MA',description:'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque eu tempor sapien, id mattis nulla. Suspendisse nec.'}],
      education:[{school:'Rocheseter Institute,', degree:'Bachelor of Engineer, New Haven, CT'},{school: 'Albertus Magnus Tech', degree:'Engineering Degree, New Haven, CT' }]},
    { id: 3, firstName: 'Colleen', lastName: 'Jones', age: 21, location: 'New York',experience:[{Title:'Director, Software Engineering',
      companyInfo:'ACME Systems, Concord, MA',
      description:'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque eu tempor sapien, id mattis nulla. Suspendisse nec lectus eros. Aenean convallis eros nec'},
      {Title:'Software Developer',companyInfo:'Universe Exports, Billerica, MA',description:'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque eu tempor sapien, id mattis nulla. Suspendisse nec'},
      {Title:'Software Specialist',companyInfo:'Universe Exports, Billerica, MA',description:'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque eu tempor sapien, id mattis nulla. Suspendisse nec.'}],
      education:[{school:'Rocheseter Institute,', degree:'Bachelor of Engineer, New Haven, CT'},{school: 'Albertus Magnus Tech', degree:'Engineering Degree, New Haven, CT' }] },
    { id: 4, firstName: 'Madelyn', lastName: 'Green', age: 18, location: 'North Dakota',experience:[{Title:'Director, Software Engineering',
      companyInfo:'ACME Systems, Concord, MA',
      description:'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque eu tempor sapien, id mattis nulla. Suspendisse nec lectus eros. Aenean convallis eros nec'},
      {Title:'Software Developer',companyInfo:'Universe Exports, Billerica, MA',description:'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque eu tempor sapien, id mattis nulla. Suspendisse nec'},
      {Title:'Software Specialist',companyInfo:'Universe Exports, Billerica, MA',description:'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque eu tempor sapien, id mattis nulla. Suspendisse nec.'}],
      education:[{school:'Rocheseter Institute,', degree:'Bachelor of Engineer, New Haven, CT'},{school: 'Albertus Magnus Tech', degree:'Engineering Degree, New Haven, CT' }] },
    { id: 5, firstName: 'Ella', lastName: 'Jobs', age: 18, location: 'South Dakota',experience:[{Title:'Director, Software Engineering',
      companyInfo:'ACME Systems, Concord, MA',
      description:'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque eu tempor sapien, id mattis nulla. Suspendisse nec lectus eros. Aenean convallis eros nec'},
      {Title:'Software Developer',companyInfo:'Universe Exports, Billerica, MA',description:'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque eu tempor sapien, id mattis nulla. Suspendisse nec'},
      {Title:'Software Specialist',companyInfo:'Universe Exports, Billerica, MA',description:'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque eu tempor sapien, id mattis nulla. Suspendisse nec.'}],
      education:[{school:'Rocheseter Institute,', degree:'Bachelor of Engineer, New Haven, CT'},{school: 'Albertus Magnus Tech', degree:'Engineering Degree, New Haven, CT' }] },
    { id: 6, firstName: 'Landon', lastName: 'Gates', age: 11, location: 'South Carolina',experience:[{Title:'Director, Software Engineering',
      companyInfo:'ACME Systems, Concord, MA',
      description:'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque eu tempor sapien, id mattis nulla. Suspendisse nec lectus eros. Aenean convallis eros nec'},
      {Title:'Software Developer',companyInfo:'Universe Exports, Billerica, MA',description:'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque eu tempor sapien, id mattis nulla. Suspendisse nec'},
      {Title:'Software Specialist',companyInfo:'Universe Exports, Billerica, MA',description:'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque eu tempor sapien, id mattis nulla. Suspendisse nec.'}],
      education:[{school:'Rocheseter Institute,', degree:'Bachelor of Engineer, New Haven, CT'},{school: 'Albertus Magnus Tech', degree:'Engineering Degree, New Haven, CT' }] },
    { id: 7, firstName: 'Haley', lastName: 'Guthrie', age: 35, location: 'Wyoming',experience:[{Title:'Director, Software Engineering',
      companyInfo:'ACME Systems, Concord, MA',
      description:'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque eu tempor sapien, id mattis nulla. Suspendisse nec lectus eros. Aenean convallis eros nec'},
      {Title:'Software Developer',companyInfo:'Universe Exports, Billerica, MA',description:'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque eu tempor sapien, id mattis nulla. Suspendisse nec'},
      {Title:'Software Specialist',companyInfo:'Universe Exports, Billerica, MA',description:'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque eu tempor sapien, id mattis nulla. Suspendisse nec.'}],
      education:[{school:'Rocheseter Institute,', degree:'Bachelor of Engineer, New Haven, CT'},{school: 'Albertus Magnus Tech', degree:'Engineering Degree, New Haven, CT' }] },
    { id: 8, firstName: 'Aaron', lastName: 'Jinglehiemer', age: 22, location: 'Utah',experience:[{Title:'Director, Software Engineering',
      companyInfo:'ACME Systems, Concord, MA',
      description:'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque eu tempor sapien, id mattis nulla. Suspendisse nec lectus eros. Aenean convallis eros nec'},
      {Title:'Software Developer',companyInfo:'Universe Exports, Billerica, MA',description:'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque eu tempor sapien, id mattis nulla. Suspendisse nec'},
      {Title:'Software Specialist',companyInfo:'Universe Exports, Billerica, MA',description:'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque eu tempor sapien, id mattis nulla. Suspendisse nec.'}],
      education:[{school:'Rocheseter Institute,', degree:'Bachelor of Engineer, New Haven, CT'},{school: 'Albertus Magnus Tech', degree:'Engineering Degree, New Haven, CT' }] }
  ];
}
